### ISSUE TITLE
[Feature] scss function 추천

### ISSUE THREAD

**Issue by Hansanghyeon** [peterosea/geosystem#16]
https://github.com/peterosea/geosystem/blob/master/scss/partial/_variable.scss

이거 추천드립니다 ㅎㅎ!

```scss
// Responsive Web Design
$breakpoints: (
  "sm": (
    min-width: 576px
  ),
  "md": (
    min-width: 768px
  ),
  "lg": (
    min-width: 992px
  ),
  "xl": (
    min-width: 1200px
  ),
  "hg": (
    min-width: 1240px
  )
);
/// Responsive breakpoint manager
/// @access public
/// @param {String} $breakpoint - Breakpoint
/// @requires $breakpoints
@mixin respond-to($breakpoint) {
  $raw-query: map-get($breakpoints, $breakpoint);

  @if $raw-query {
    $query: if(
      type-of($raw-query) == "string",
      unquote($raw-query),
      inspect($raw-query)
    );

    @media #{$query} {
      @content;
    }
  } @else {
    @error 'No value found for `#{$breakpoint}`. '
			+ 'Please make sure it is defined in `$breakpoints` map.';
  }
}

// Use
@include respond-to('sm') {
  body {
    height: 100%;
  }
}
```
